### ISSUE TITLE
Change abbyy Windows paths

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/common-accessioning#1348]
Abbyy Window paths are changing from an E drive to an S drive.  We need to update all shared_configs and fixtures that reference the E drive to an S drive.

Coordinate change with Ops and Andrew/Tony since they should be done together with other changes that needed to happen on the mounts.

see https://stanfordlib.slack.com/archives/C06EVDJV45N/p1726602414018549 and https://stanfordlib.slack.com/archives/C06EVDJV45N/p1726602734053849

Need to change these settings in 

1. `config/settings/test.yml` file (see section below)
2. Test fixtures that reference `E:\`
3. Shared_configs for all environments:
- https://github.com/sul-dlss/shared_configs/blob/common-accessioning-prod/config/settings/production.yml#L19-L24
- https://github.com/sul-dlss/shared_configs/blob/common-accessioning-qa/config/settings/production.yml#L20-L25
- https://github.com/sul-dlss/shared_configs/blob/common-accessioning-stage/config/settings/production.yml#L20-L25

Once shared_configs changes are merged, de-deploy, re-run OCR integration tests to verify.

```
sdr:
  local_workspace_root: /dor/workspace
  abbyy:
    # Windows-style paths for the ABBYY machine, referenced in XML tickets
    remote_output_path: E:\AbbyyShare\sdr-ocr-qa\OUTPUT
    remote_result_path: E:\AbbyyShare\sdr-ocr-qa\RESULTXML
```
